name: Deploy Vite React App to GitHub Pages

on:
  push:
    branches:
      - main # MUITO IMPORTANTE: Se o seu branch principal no GitHub for 'master', mude esta linha para '- master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Versão do Node.js
          cache: 'npm' # Habilita cache para npm install

      - name: Install dependencies
        run: npm install

      - name: Build React App with Vite
        run: npm run build # Comando para construir seu aplicativo Vite

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # ONDE O SEU SITE É GERADO (pasta 'dist' para Vite)
          publish_branch: gh-pages # O BRANCH QUE O GITHUB PAGES VAI LER
